import math 
import numpy as np
from collections import Counter
from fastapi import FastAPI
from pydantic import BaseModel
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
import re
import requests 


app = FastAPI()
console = Console()

class QueryItem(BaseModel):
    prompt: str

def calculate_entropy(text):
    if not text:
        return 0.0
    
    frequencies = Counter(text)
    length = len(text)
    entropy = 0.0

    for count in frequencies.values():
        probability = count / length

        entropy -= probability*math.log2(probability)

    return round(entropy,2)

normal_data = np.array([
    # Short questions (like "who wrote hamlet")
    [15, 2.8], [16, 3.2], [12, 2.5], [18, 3.0], [20, 3.4],
    # Medium questions
    [30, 3.5], [45, 3.8], [28, 3.2], [50, 4.0], [35, 3.6],
    # Long, complex questions
    [75, 4.2], [90, 4.5], [65, 4.0], [110, 4.8], [85, 4.3]
])

mean_data = np.mean(normal_data , axis = 0)
cov_matrix = np.cov(normal_data , rowvar = False)
inv_cov_matrix = np.linalg.inv(cov_matrix)

def calculate_anomaly_score(text_length:int, entropy:float) -> float:
    x = np.array([text_length, entropy])
    diff = x - mean_data
    distance = np.sqrt(np.dot(np.dot(diff, inv_cov_matrix), diff.T))
    return round(distance, 2)

RISKWORDS = {"ignore", "bypass", "system", "prompt", "instructions", "admin", "password", "override", "root", "access", "privilege", "escalate", "exploit", "vulnerability", "attack", "malicious"}

def calculate_risk_score(text: str) -> float:
    words = text.lower().split()
    if not words:
        return 0.0
    
    risk_word_count = sum(1 for word in words if word in RISKWORDS)
    probability = min(risk_word_count / 3.0, 1.0)
    return round(probability , 2)

training_texts = [
    # Added physics/science words to the Math cluster
    "what is 2+2", "calculate the derivative", "solve for x math", "physics newton gravity equations", 
    # Added "error" to the Code cluster
    "write a python script", "debug this code", "html css javascript", "syntax error",
    # Added geography to the General cluster
    "what is the capital of france", "who wrote hamlet", "explain history", "geography map" 
]
vectorizer = TfidfVectorizer(stop_words='english', token_pattern=r"(?u)\S+")
X = vectorizer.fit_transform(training_texts)
kmeans = KMeans(n_clusters = 3 , random_state = 42 , n_init = 10)
kmeans.fit(X)
cluster_labels = {0: "General Knowledge", 1: "Programming", 2: "Mathematics"}
def categorize_topic(text: str) -> str:
    if re.search(r"[\d\+\-\*\/=]+", text) and any(char.isdigit() for char in text):
        return "Mathematics"
    
    vec = vectorizer.transform([text.lower()])
    cluster_id = kmeans.predict(vec)[0]
    return cluster_labels.get(cluster_id, "Unknown")


def query_ollama(prompt: str , destination: str) -> str:
    if "Fast" in destination:
        model_name = "tinyllama"
    else:
        model_name = "llama3.2"

    ollama_url = "http://localhost:11434/api/generate"
    payload = {
        "model" : model_name,
        "prompt" : prompt,
        "stream" : False
    }

    try:
        response = requests.post(ollama_url, json=payload)
        response.raise_for_status() 
        data = response.json()
        return f"[Generated by {model_name}] -> " + data.get("response", "Error: No response generated.")
    except requests.exceptions.RequestException as e:
        return f"[CONNECTION ERROR] -> Could not connect to Ollama. Is the Ollama app running? Error: {e}"






@app.post("/route")
def route_query(item: QueryItem):
    length = len(item.prompt)
    entropy_score = calculate_entropy(item.prompt)
    anomaly_score = calculate_anomaly_score(length , entropy_score)
    risk_score = calculate_risk_score(item.prompt)
    topic = categorize_topic(item.prompt)

    # 1. Determine Status & UI Variables
    if anomaly_score > 10.0:
        status = "BLOCKED (Anomaly)"
        color = "bold red"
        destination = "None"
    elif risk_score >= 0.66:
        status = "BLOCKED (High Risk)"
        color = "bold red"
        destination = "None"
    else:
        status = "ROUTED"
        color = "bold green"
        
        # --- THE NEW SEMANTIC INTENT FILTER ---
        word_count = len(item.prompt.split())
        
        # Words that require deep reasoning or factual recall
        deep_thinking_words = {"explain", "why", "how", "principle", "theory", "concept", "summarize", "analyze"}
        
        # Check if any deep-thinking words are in the user's prompt
        requires_deep_thought = any(word in item.prompt.lower() for word in deep_thinking_words)

        # The Ultimate Routing Decision
        if requires_deep_thought:
            destination = "Heavy LLM"
        elif entropy_score < 4.2 and word_count < 8:
            destination = "Fast Cache"
        else:
            destination = "Heavy LLM"
    
    table = Table(title="AETHER-FLOW Query Analysis", style="bold cyan")
    table.add_column("Metric" , style="bold magenta")
    table.add_column("Value" , style="bold yellow")

    table.add_row("Topic" , topic)
    table.add_row("Complexity Score" , str(entropy_score))
    table.add_row("Mahalanobis Distance" , str(anomaly_score))

    table.add_row("Bayesian Risk Score" , str(risk_score))
    table.add_row("Status" , f"[{color}]{status}[/]")
    table.add_row("Destination" , destination)

    console.print(Panel(table, border_style="blue", title=f"New Query: '{item.prompt}'"))

    if status.startswith("BLOCKED"):
        return {"status": "BLOCKED", "reason": status, "metrics": {"anomaly": anomaly_score, "risk": risk_score}}
    
    ai_answer = query_ollama(item.prompt , destination)

    return {
        "status": "SUCCESS",
        "user_prompt": item.prompt,
        "topic": topic,
        "metrics": {
            "complexity_score": entropy_score,
            "anomaly_score": anomaly_score,
            "risk_score": risk_score
        },
        "routing": {
            "destination": destination,
        },
        "ai_response": ai_answer
    }
